# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.7"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    tty: true
  chrome-node-1:
    image: selenium/node-chrome:latest
    build:
      context: .
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    tty: true
  chrome-node-2:
    image: selenium/node-chrome:latest
    build:
      context: .
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    tty: true
  chrome-node-3:
    image: selenium/node-chrome:latest
    build:
      context: .
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    tty: true
  chrome-node-4:
    image: selenium/node-chrome:latest
    build:
      context: .
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    tty: true
